# -*- coding: utf-8 -*-
"""Linear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w_-MGZGaenIP0mlKGstWN_EUDISf39dS
"""

import pandas as pd

df= pd.read_csv("/content/Salary_Data.csv")

df.head()

df.info()

df.isna().sum()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,6))

sns.histplot(data = df, x = "Age", color ="teal" ,kde=True)
plt.title("Distribution of Age")
plt.show()

plt.figure(figsize=(10,6))

sns.countplot(data = df, x ="Education Level", hue= "Education Level", palette = "pastel")

plt.show()

plt.figure(figsize=(10,6))

sns.countplot(data = df, x ="Gender" , hue = "Gender" , palette ="Blues")

plt.show()

plt.figure(figsize=(10,6))

sns.histplot(data = df, x = "Years of Experience", color = "Red", kde = True)
plt.title("Distribution of Years of Experience")
plt.show()

plt.figure(figsize=(10,6))

sns.histplot(data = df, x = "Salary" , color = "Magenta", kde =True)
plt.title("Distribution of Salary")
plt.show()

df.describe()

df["Gender"].unique()

df["Education Level"].unique()

df["Education Level"] = df["Education Level"].replace({"Bachelor's Degree":"Bachelor's" ,"Master's Degree" :"Master's" , "phD" : "PhD"})

df["Education Level"].unique()

df["Job Title"].unique()

df["Job Title"].nunique()

df.dropna(inplace =True)

X = df.drop(columns = "Salary" )
y = df["Salary"]

X

from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X,y , test_size = 0.2 , random_state = 42)

from sklearn.preprocessing import StandardScaler , OneHotEncoder , LabelEncoder

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

cat_col = ["Gender","Education Level" , "Job Title"]

num_col = ["Age","Years of Experience"]

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_col),
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_col)
    ])

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model_pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                               ('regressor', model)])

model_pipeline.fit(X_train, y_train)

y_pred_pipeline = model_pipeline.predict(X_test)

print(y_pred_pipeline[:5])

